### ISSUE TITLE
Small compile issue on Centos 7 

### ISSUE THREAD

**Issue by rubytastic** [MonaSolutions/MonaServer#10]
On CentOS there is a small compile issue with the sources not finding the include.

sources/Script.h:27:29: fatal error: luajit-2.0/lua.h: No such file or directory

I tried to place this folder in the sources and other subfolders to no avail. Where should the luajit folder be placed?

**Comment by thomasjammet** [comment]
Have you installed the luajit on your system? On CentOS I think the command
is :

su -c "make install"

*--*

*Thomas JAMMET*
Freelancer - MonaServer.ovh
2 Rue Mila - 82000 Montauban (France)
Tel : *+336 23 46 39 80*
http://fr.linkedin.com/pub/thomas-jammet/5a/411/60b/

2015-02-17 16:25 GMT+01:00 rubytastic <notifications@github.com>:

**Comment by rubytastic** [comment]
Yes its , 
make
make install 

The latter command fails, could not find any reference in the documents why no install command.

So make does:
...
LINK      luajit
OK        Successfully built LuaJIT

make install
make: *** No rule to make target `install'.  Stop.

Try to investigate further, anyone else have this issue? 
Now just compiling on CentOS later look at OSX

**Comment by thomasjammet** [comment]
I think you are is in the wrong directory, you must execute "make" in the
root directory of luajit-2.0.

*--*

*Thomas JAMMET*
Freelancer - MonaServer.ovh
2 Rue Mila - 82000 Montauban (France)
Tel : *+336 23 46 39 80*
http://fr.linkedin.com/pub/thomas-jammet/5a/411/60b/

2015-02-17 16:40 GMT+01:00 rubytastic <notifications@github.com>:
