### ISSUE TITLE
Netstream.send?

### ISSUE THREAD

**Issue by jespermjonsson** [MonaSolutions/MonaServer#12]
I'm trying to migrate from Wowza to MonaServer so I can utilize the RTMFP protocol, but I also want to have the same RTPM protocol functionallity. But it seems that Netstream.send("myHandler", "some data") isn't working as I expected. The netstream client function "myHandler" isn't called as it was when using Wowza. Is this something that should work? I'm trying to embed data into the video stream that is sent to the other party alongside the video and triggered at the exact seekTime as it was sent.

**Comment by MathieuPOUX** [comment]
Mmmm strange, should, I use it a lot, it happens just with RTMP or RTMFP
too?

2015-05-05 18:12 GMT+02:00 Jesper Jonsson <notifications@github.com>:

**Comment by jespermjonsson** [comment]
I have only tested with RTMP so far. I'm using a server application so there is some logic (in main.lua) that I call using NetConnection.call and on the NetConnection there is client with an "onBroadcast" handler that the server calls, don't know if that interferes with the NetStream also having an client, but it worked with Wowza so I guess it shouldn't. But since you say that it should work I'll investigate further.. If I don't find anything I'll try to extract the code so I can show you a more complete example of my use case.

**Comment by thomasjammet** [comment]
Hi Jesper,

I have tested and it only works with RTMFP. Don't loose your time to
investigate, we will resolve this problem as soon as possible.

Until this issue is not resolved you can add this code in the main.lua :

function onConnection(client)
function client:onPublish(publication)
     -- Send messages from publisher to listeners
function publication:onData(name,packet)
    INFO("New Message : ", name, " ; ", packet)
    for listener, nothing in pairs(publication.listeners) do
        listener.client.writer:writeInvocation(name, packet)
    end
end
end
end

It should do what you want.

*--*

*Thomas JAMMET*

2015-05-06 9:04 GMT+02:00 Jesper Jonsson <notifications@github.com>:

**Comment by jespermjonsson** [comment]
Ok, that works :+1: But isn't that the same as just using NetConnection.call? It seems that the messages arrive earlier than the video point where they happened on the publisher (which is why I was using NetStream.send).

**Comment by thomasjammet** [comment]
Hi Jesper,

I have just made a correction to make it works with RTMP, tell us if your problem is resolved.

Thanks

**Comment by jespermjonsson** [comment]
Ok thanks, I'll try it out. :) Will be on a vacation for a week so I'll let you know after that!
