### ISSUE TITLE
client variable (at init time) => mona lua server variable?

### ISSUE THREAD

**Issue by rubytastic** [MonaSolutions/MonaServer#13]
We have publication.name

But, how would I pass additional variables at initializing timefrom the client to the mona lua server application? I only need them to be set once, the most simple way possible. 

Could you provide an example on how to do this? 

Kind regards and keep up the good work!

**Comment by MathieuPOUX** [comment]
Not sure to understand exactly, but I try a response :-)

1 - You can initialize your "server application" variable in your
www/app/main.lua file as global variable, it will reinitialized on every
application reloading:

_name = "value"

function onConnection(client,...)
end


2 - You use onStart(path) event, it will reinitialized on every application
reloading:

function onStart(path)
   _name = "value"
end


3 - You can use MonaServer.ini file to set any custom parameters:
; MonaSerber.ini file

name=value ; => custom "name" parameter
[RTMFP]
port=19350 ; => known "RTMFP.port" parameter, change RTMFP port
[category]
name=value ;  => custom "category.name" parameter


Now you can access for these parameters simply like that:

NOTE("RTMFP.port = ",mona.RTMFP.port)
NOTE("name = ",mona.RTMFP.port)
NOTE("category.name = ",mona.category.name)


Also you can use also "mona.parameters" table:

for key,value in pairs(mona.parameters) do
   NOTE("Ini parameter => ",key,value)
end


2015-05-15 17:06 GMT+02:00 rubytastic <notifications@github.com>:

**Comment by rubytastic** [comment]
Thank you for your response MathieuPOUX

Im looking to pass a variable from the SWF client => Mona main.lua
Not sure how above examples would help in that, they are fixed values. 
Is there a good simple way to pass a variable to the main.lua ?

**Comment by thomasjammet** [comment]
Hi rubytastic,

I think we need more informations on your use case. Tell us exactly what
you want to do.

If you want to call a server function from your client (RPC) you just need
to call *"netConnection.call"* from the AS3 scripts (take a look at the 6st
slide in our Quickstart's guide <http://www.monaserver.ovh/quickstart.html>
).

You could also pass parameters in the *AS3 "netConnection.connect()"*
command, they will be add into the lua callback function
*onConnection(client,parameters)*.

Or if you want to add a parameter into a publication you could use this
line :
ns.send("@setDataFrame", "onMetaData", metaDataObject);
*onMetaData* will be called in each listener netStream at the moment of the
ns.send command or at the start of a the new listeners.

Tell us if it helps you

*--*

*Thomas JAMMET*
http://fr.linkedin.com/pub/thomas-jammet/5a/411/60b/

2015-05-16 11:31 GMT+02:00 rubytastic <notifications@github.com>:

**Comment by rubytastic** [comment]
Hi Thomas,

Goal is to provide variable called "path" 

I now have:
function onConnection(client, parameters)
  ..
	function client:onPublish(publication)
           get custom parameters here
       end
end

My AS is terrible, could you please provide an example on how to correctly pass parameters from SWF client to Mona that way? Kind regards

**Comment by thomasjammet** [comment]
Hi,

I think the best way to do what you want is to call a remote lua function
from AS3, take a look at this paragraph :
http://www.monaserver.ovh/serverapp.html#pull-data-remote-procedure-call,
it provides some examples.

Then in the lua code you can record a global variable :
*globalPath *= nil
function onConnection(client,...)
  function client:remoteFunction(pathVariable)
    *globalPath *= pathVariable
  end
  function client:onPublish(publication)
    -- do what you want here with globalPath
  end
end

Or you can also record a variable directly in the client object :
function onConnection(client,...)
  function client:remoteFunction(pathVariable)
    *client.pathVar* = pathVariable
  end
  function client:onPublish(publication)
    -- do what you want here with client.path
  end
end

*Note :* Be careful because there is already a variable named "path" in the
client object.

*--*

*Thomas JAMMET*
http://fr.linkedin.com/pub/thomas-jammet/5a/411/60b/

2015-05-18 15:47 GMT+02:00 rubytastic <notifications@github.com>:

**Comment by MathieuPOUX** [comment]
You can use also connection parameters, or publication parameters:

var prop1="val1";
_netConnection.connect("rtmfp://address/appli?prop2=val2",prop1);
...
_netStream.pubish("test?prop3=val3");


function onConnection(client,prop1)
     NOTE("prop1 = ",prop1)
     NOTE("prop2 = ",client.prop2)
     function client:onPublish(publication)
          NOTE("prop2 = ",self.prop2)
          NOTE("prop3 = ",publication.prop3)
     end
end


2015-05-19 13:18 GMT+02:00 Thomas Jammet <notifications@github.com>:

**Comment by rubytastic** [comment]
I tried:

_netConnection.connect("rtmfp://address/appli?mypath=xyz");

Then your client code above only the variable is not coming true.
For now that solution seemed to be the most simple less elegant though.

I restarted Mona and compiled my SWF again still the value is null

**Comment by MathieuPOUX** [comment]
if you have closed the ticket it means that it works finally?

2015-05-19 19:45 GMT+02:00 rubytastic <notifications@github.com>:

**Comment by rubytastic** [comment]
Hi  MathieuPOUX 
I managed to resolve the issue. 
The Connection param string was not correct ( I was using VideoPublisher example ) after correcting this I was able to get the variables contents.
