### ISSUE TITLE
compiling on Debian

### ISSUE THREAD

**Issue by breign** [MonaSolutions/MonaServer#14]
For solving compilation error 
**'/usr/bin/ld: //usr/local/lib/libluajit-5.1.a(lj_clib.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'**
I had to change **CFLAGS+=-std=c++11** to **CFLAGS+=-std=c++11 -ldl** in MonaServer/Makefile on Debian7

**Comment by MathieuPOUX** [comment]
Interesting, what is "-ldl" compilor parameter?

2015-05-19 11:56 GMT+02:00 Benjamin Povirk <notifications@github.com>:

**Comment by breign** [comment]
dladdr, dlclose, dlerror, dlopen, dlsym, dlvsym - programming interface to dynamic linking loader

**Comment by MathieuPOUX** [comment]
Thanks, It has been added for the next commit.

Best,
Mathieu

2015-05-19 13:48 GMT+02:00 Benjamin Povirk <notifications@github.com>:
