### ISSUE TITLE
Number of clients >0

### ISSUE THREAD

**Issue by garybruckheimer** [MonaSolutions/MonaServer#18]
I try to get the number of connected clients and some infos about the clients in a lua server script.

Every time when a new client connects, i print out in a shell the client.address and id, like this.

function onConnection(client,...)
    for id, client in pairs(mona.clients) do
        INFO(id, " : ", client.address)
    end
end

The for function only works when 2 clients are connected where it only prints the address of connected client 2. It seems that client 1 is not in the mona.clients. 

For debuging when i connect only one client i used:

function onConnection(client,...)
    for id, client in pairs(mona.clients) do
        INFO(id, " : ", client.address)
    end
    INFO(client.address)
end

I got client.address when i connect only with one client.

Is this maybe an bug i do oversee something from the point of lua scripting?

**Comment by thomasjammet** [comment]
Hi Gary,

I think there is a confusion in the variable definitions. You have defined the variable "client" twice so the result is unpredictable 

Try to change the loop line with :
```lua
for id, c in pairs(mona.clients) do
  INFO(id, ":", c.address)
end
```
