### ISSUE TITLE
compiling into docker container

### ISSUE THREAD

**Issue by rubytastic** [MonaSolutions/MonaServer#19]
compiling in docker throws the following error:

sources/Application.cpp[191] !ex assertion, sources/DNSTest.cpp[51]

any thoughts on how to resolve these?

**Comment by breign** [comment]
if you need working docker, here it is https://registry.hub.docker.com/u/breign/ubuntu-monaserver/

**Comment by rubytastic** [comment]
Resolved by disabling the tests, thank you for posting I will be checking your docker file on how to compile it correctly.
