### ISSUE TITLE
PoolBuffers::endBuffer Strategy issue 

### ISSUE THREAD

**Issue by chrislong2015** [MonaSolutions/MonaServer#21]
1、void PoolBuffers::endBuffer(Buffer* pBuffer) const {
2、	if (pBuffer->capacity() > _maximumCapacity) {
3、		delete pBuffer;
4、		return;
5、	}
6、	pBuffer->clear(); //to fix clip, and resize to 0
	......
}

should we take line 6 before line 2?

**Comment by reatailret** [comment]
"return" on line 4 .

**Comment by chrislong2015** [comment]
line 2: the capacity maybe not the real capacity,it can have been changed by clip()?

**Comment by MathieuPOUX** [comment]
Hi,

I had a algo redesign for PoolBuffers/PoolBuffer that I share now by this last commit =>
https://github.com/MonaSolutions/MonaServer/commit/5f92bb26b6ce9c3c286a5656c821487347d304ab
Works a lot better, let me know if it solves your memory issue.
+

**Comment by chrislong2015** [comment]
Hi,
I think it still has a problem, because of the possible clip(), _capacity would have been changed.

1、
void Buffer::clip(UInt32 offset) {
	if (offset > _size)
		offset = _size;
	if (offset == 0)
		return;
	_offset += offset;
	_data += offset;
	_size -= offset;
	_capacity -= offset;
}

2、
UInt32 capacity() const { return _capacity; }

3、
void release() { if (!_pBuffer) return; poolBuffers.endBuffer(_pBuffer); _pBuffer = NULL; }

4、
void PoolBuffers::endBuffer(Buffer* pBuffer) const {
	lock_guard<mutex> lock(_mutex);
	_buffers.emplace(pBuffer->capacity(),pBuffer);
}

**Comment by MathieuPOUX** [comment]
Yes you are right, on my next commit I will solve it by the following fix:

void PoolBuffers::endBuffer(Buffer* pBuffer) const {
pBuffer->clear();
lock_guard<mutex> lock(_mutex);
_buffers.emplace(pBuffer->capacity(),pBuffer);
}

Thanks

**Comment by chrislong2015** [comment]
Thanks! I think it will work better now!
