### ISSUE TITLE
Errors when large concurrent users join

### ISSUE THREAD

**Issue by alexea** [MonaSolutions/MonaServer#24]
Does there anybody happen these problems?
One publication (camera video and audio) and about 80 players.
1. RTMFP\RTMFPWriter.h[62] RTMFPWriter 4 has failed, RTMFPWriter can't deliver its data, Repeat trigger failed
1. RTMFP\RTMFPSession.cpp[450] RTMFPFlow 7 unfound
   RTMFP\RTMFPFlow.cpp[127] RTMFPFlow 7 failed, RTMFPMessage received for a RTMFPFlow unknown
2. RTMFP\RTMFPSession.cpp[402] RTMFPWriter 71 unfound for acknowledgment on session RTMFP session 80

**Comment by thomasjammet** [comment]
Hi alexea,

80 players is not so much.

Could you tell us more about your issue :
- Does it happens again or it was a one time error? 
- Can you reproduce the issue?
- What version of Mona do you use?

**Comment by alexea** [comment]
Does it happens again or it was a one time error?
Almost every time.
Can you reproduce the issue?
Yes.
What version of Mona do you use?
The latest version.

What information else will you need?
I can reproduce it and send to you. thanks.

**Comment by thomasjammet** [comment]
Ok, can you send me the lua files by mail and the way to reproduce the issue? 

Thanks

**Comment by alexea** [comment]
Here is no lua file. I just config the MonaServer.ini file as follows:
[RTMFP]
port = 3035
[RTMP]
port = 3035
[HTTP]
port = 8081
[RTSP]
port = 8554

Publish one publication (camera video and audio) to MonaServer with the latest windows version.
MonaServer can support over 100 players using H.263 and speex codecs. But it just supports about 20 players using H.264 and speex codecs.
I have sent the test program to you by email.

**Comment by thomasjammet** [comment]
It looks like a network issue, this can be due to congestion. 
If someone has always these errors coming often let's try [MonaTiny (MonaServer2)](https://github.com/MonaSolutions/MonaServer2).
