### ISSUE TITLE
VideoWisper RTMP web server code used in MonaServer

### ISSUE THREAD

**Issue by dipenpatel235** [MonaSolutions/MonaServer#25]
Hello,
We want to used red5 based web package to used in Monaserver Web 
So How can i migrate/modify  that.
Please Contact me : dipen.ec2010@gmail.com if you  have knowledge on that

**Comment by thomasjammet** [comment]
Hi dipen,

I think it's possible to do it yourself if you have knowledge of programming and are not afraid of debugging with lua. 

I have sent you a mail with more infos,
