### ISSUE TITLE
strange data in Listener.parameters

### ISSUE THREAD

**Issue by gokiburikin** [MonaSolutions/MonaServer#31]
in an attempt to pass additional information to the server through a flashplayer url (eg; `/myapplication/streams/streampath?info=0123456789`) i noticed that the `Listener` from `client:onSubscribe` has an undocumented parameters value that seems to hold up to 15 valid characters that are equivalent to the URL query string passed in, but once more than 15 characters are passed the data become unintelligible.

a query of `?012345678901234` produces `Listener.parameters (012345678901234)`
a query of `?0123456789012345` produces `Listener.parameters (Pｩ♣♦・・pv・後睆►)`

i'm not sure what is happening with this potentially useful variable, but it seems unintentional

**Comment by thomasjammet** [comment]
I think it is corrected now, I have also added this argument into the documentation.
