### ISSUE TITLE
RTMP with path does not work?

### ISSUE THREAD

**Issue by rooi** [MonaSolutions/MonaServer#32]
Hi,

I'm using OBS to send a stream to OBS and use VLC 2.1.5 to view this stream as client. I'm trying to update the VLC version to get better recording stability, but the path (rtmp://127.0.0.1:1935/path) does not work with later version of VLC (in combination with OBS).

I investigated this further by building MonaServer myself and noticed that VLC behaves differently when opening the service (Service* Service::open(Exception& ex, const string& path)). With old VLC version 2.1.5 the path has no value, while new VLC version have a path specified.
Furthermore, I noticed that when setting up the OBS stream to MonaServer the path is not set. When tracing this in the debugger, the following does not seem to contain or extract the path specified in OBS:

void Peer::onConnection(Exception& ex, Writer& writer,DataReader& parameters,DataWriter& response)

It seems that the RTMP stream with path specified is not implemented (correctly), or there is something wrong in OBS. Could someone please comment on this?

I would like to use the path because I have multiple streams coming from the same machine and would like to distinguish them using the path.

Thanks!

Roy

**Comment by thomasjammet** [comment]
Hi rooi,

I am not sure to understand what doesn't work but I will try to explain what you should do for publishing multiple streams from the same machine and play them on VLC.

Firstly I think you should take a look at [Create a server application](http://www.monaserver.ovh/serverapp.html#create-a-server-application) to know what the path of an url means in MonaServer. 
To resume : 
Every directory in the "www" directory of MonaServer is an application. When you publish a stream to *rtmfp://127.0.0.1/dir1/subdir1/test123* it will open a connection to the application "subdir2" which is part of application "dir1" and finally will create the publication "test123".

Now to publish from OBS you need to : 
- specify the FMS URL (rtmp://127.0.0.1/)
- and the name of the publication (*test1* for example)

**Note:** As you can see in the last version of OBS specifying an application is not needed.

On VLC it is needed to specify an application so  you could see your stream *test1* with the following url :
*rtmp://127.0.0.1/dir1/test1*

And now to publish other streams from OBS you can change the name of the publication and publish again.

I hope this answer to your question!

Regards

**Comment by rooi** [comment]
Thanks it works using your tips ;)
