### ISSUE TITLE
P2P rendezvous/introduction server help

### ISSUE THREAD

**Issue by wini3d** [MonaSolutions/MonaServer#34]
Hi, I would like to know how to create a simple p2p server app similar to what the test Cirrus Servers are doing here: **p2p.rtmfp.net**. It seems like it works on all p2p flash demos/games that I have tried and I just need a similar p2p introduction app. 

My client is responding to the monaserver that I have setup, but I'm getting these error messages when I try to connect.
```
RTMFP/RTMFPSession.h[82] Client failed, Main flow writer closed, session is closing
RTMFP/RTMFPSession.cpp[401] RTMFPWriter 2 unfound for acknowledgment on session RTMFP session 1
```

**Comment by thomasjammet** [comment]
Hi,

Sorry but I don't see which app you are talking about, could you tell us more?

The following log is important :
"sources/MonaServer.cpp[483] Application /c7567acba205bb6aa5e4a31c-82bc3fb60ac5 doesn't exist"
I don't see it anymore in this Issue but it means that you send a connection request with the wrong parameters.

Take a look at our [samples](www.monaserver.ovh/samples.html) if you need help to start writing apps. MonaVideo is the simplest p2p app that you could find. Note that all source code is here : https://github.com/MonaSolutions/MonaClients

Ask us if you don't understand the code.

Regards

**Comment by wini3d** [comment]
Hi @thomasjammet and thanks for the response. Basically, I just need a simple P2P rendezvous service to start with, similar to the cirrus test servers at rtfmp://p2p.rtmfp.net. 

Maybe related to Netgroup and a server backend for this tutorial/resource:

http://blog.andrewwalpole.com/2013/02/27/introducing-netgrouper-for-easy-real-time-rtmfp-p2p-connections-between-swfs/

**Comment by thomasjammet** [comment]
Ok so I think you just need to remove the Cirrus key (the 2 parameter of the NetConnection constructor if I remember well)

Otherwise show us your code to see what's going on.

**Comment by wini3d** [comment]
Yes, I got that one out of the way, thanks. I'm currently trying out some p2p libraries like this [AS3Mul](https://github.com/reyco1/as3mul). Here's the example source with the library:

http://www.rhuno.com/Downloads/AS3MUL_Tutorial_Rhuno.zip

**Comment by thomasjammet** [comment]
Ok I see, if you need help for coding your flex p2p apps you can contact us. This is quite easy, also without using libraries.

**Comment by wini3d** [comment]
Hi, sorry for the late reply. Ok, if this is quite easy for you guys, can you just include an example for this P2P rendezvous stuff? 

Also, please mark this issue as a feature request instead.

Thanks.

**Comment by thomasjammet** [comment]
Hi wini3d,

First, sorry for the late reply,

Does this function is clear enough for you : 
https://github.com/MonaSolutions/MonaClients/blob/master/MonaVideo/src/MonaVideo.mxml#L139 ?
This is the source code of one of our client [samples](http://www.monaserver.ovh/samples.html).

The principle is easy to understand. After a successful connection to the server you can create and publish an outgoing stream with these lines :

```
_outgoingStream = new NetStream(_connection, NetStream.DIRECT_CONNECTIONS);
_outgoingStream.publish(caller? "caller" : "callee");
_outgoingStream.attachAudio(_mic);
_outgoingStream.attachCamera(_cam);
```

And then you can create and listen to an incoming stream with the code below :

```
_incomingStream = new NetStream(_connection, id); // id is the 32 bytes ID of the peer
_incomingStream.play(caller? "callee" : "caller");

// Read video!
_remoteVideo = new Video();
_remoteVideo.x = _remoteVideo.y = 0;
_remoteVideo.width = remoteVideoDisplay.width;
_remoteVideo.height = remoteVideoDisplay.height;
_remoteVideo.attachNetStream(_incomingStream);
remoteVideoDisplay.addChild(_remoteVideo);
```

Now this was a 1-1 connection, if you are looking for multicast feature look at NetGroup and our samples using it. [VideoPublisher](http://raspi.monaserver.ovh/MonaClients/VideoPublisher/) and [Videoplayer](http://raspi.monaserver.ovh/MonaClients/VideoPlayer/?fit) allow group publication/play for example.

I hope it will help you!

Regards

**Comment by wini3d** [comment]
Thanks @thomasjammet.
