### ISSUE TITLE
Happen Session RTMP session 1 died

### ISSUE THREAD

**Issue by dreamsxin** [MonaSolutions/MonaServer#38]
```log
sources/Session.cpp[58] peer.id ad10ebdf4b7a3b72f4d027f7ca30d2faee35ee70d6f83a956a60b1009f0828b0
sources/FlashStream.cpp[29] FlashStream 0 created
Mona/Sessions.h[106] Session RTMP session 1 created
RTMP/RTMPSession.cpp[184] headerSize>=4
RTMP/RTMPSession.cpp[194] headerSize>=12
RTMP/RTMPSession.cpp[201] streamId 0
sources/FlashMainStream.cpp[73] Client RTMP not compatible with AMF3, few complex object can be not supported
sources/Peer.cpp[209] Client 127.0.0.1:34379 connection
RTMP/RTMPSession.cpp[184] headerSize>=4
RTMP/RTMPSession.cpp[194] headerSize>=12
RTMP/RTMPSession.cpp[201] streamId 0
sources/Sessions.cpp[115] Session RTMP session 1 died
sources/FlashStream.cpp[34] FlashStream 0 deleted
```

**Comment by thomasjammet** [comment]
Hi,

Yes, it is possible that older version of RTMP are not well supported. Can you tell us what is your client so that we can try ourself? 

Regards

**Comment by dreamsxin** [comment]
@thomasjammet Hi, I use that https://github.com/shogo4405/lf.swift of iOS, If you are not with MAC, may not be able to test.

**Comment by thomasjammet** [comment]
Hi @dreamsxin,

Ok I should build a specific environment, if you want to contribute please contact me by mail. Otherwise if you know a way to reproduce the error with a linux or windows client let me know, it could help!

Regards

**Comment by dreamsxin** [comment]
@thomasjammet Hi, In client fixed it https://github.com/shogo4405/lf.swift/issues/36#issuecomment-220728241

**Comment by thomasjammet** [comment]
Great, thank you for your report!
