### ISSUE TITLE
gcc 6.1 issue

### ISSUE THREAD

**Issue by wudimeicom** [MonaSolutions/MonaServer#39]
Hello,Mr 
 the compiler output these notes:
                                                                            ^
./include/Mona/Event.h:102:4: note: in expansion of macro ‘FATAL_ERROR’
    FATAL_ERROR("Deleting function during event ", typeid(*this).name()," subscription");
    ^~~~~~~~~~~
./include/Mona/Exceptions.h:114:157: note: in C++11 destructors default to noexcept
 na::String::Format(__error,## __VA_ARGS__,", " __FILE__ "[" LINE_STRING "]"));}
                                                                             ^
./include/Mona/Event.h:102:4: note: in expansion of macro ‘FATAL_ERROR’
    FATAL_ERROR("Deleting function during event ", typeid(*this).name()," subscription");
    ^~~~~~~~~~~

best regards

**Comment by thomasjammet** [comment]
Hi wudimeicom,

Can you tell us how did you resolve your issue?

Thanks
