### ISSUE TITLE
server says things are working - screen is black

### ISSUE THREAD

**Issue by joshuroar** [MonaSolutions/MonaServer#41]
I'm using http://raspi.monaserver.ovh/MonaClients/VideoPlayer/, and I've tried Monaserver git version, compiled manually on ubuntu as well as the Windows binary build.

What information can I provide to help?

**Comment by joshuroar** [comment]
more information - I'm using obs to generate the stream. If I connect from my own computer using my external IP address, it works. If I connect from my friend's computer outside my network, I'm getting the black screen. However, the server is still indicating that things are connected.

Also, this is all rtmp, because for some reason, rtmfp doesn't seem to want to connect at all.

**Comment by joshuroar** [comment]
restarting obs (more than one time) fixed it. Is there some kind of handshaking happening over udp that can fail?

**Comment by MathieuPOUX** [comment]
Hi, strange.
No, normally 100% of handshake works, now if your firewall/router block UDP
packet of course it will not work.
Beware with OBS too, the Studio version is always a beta version (I use it
here too, but sometimes things stop to work and I have to restart it to
work again).

2016-07-04 6:31 GMT+02:00 joshuroar <notifications@github.com>:

**Comment by thomasjammet** [comment]
Any news?

Do you mean RTMFP publishing from OBS? Because this protocol is not supported by OBS for now.

If you can send us the MonaServer log (set log=8) when the connection fails.
