### ISSUE TITLE
How send other stream to client?

### ISSUE THREAD

**Issue by dreamsxin** [MonaSolutions/MonaServer#43]
In FMS main.asc：
```asc
application.onAppStart = function() {
  this.myNC= new NetConnection();  
  this.myNC.onStatus = onStatus;
  this.myNC.connect("rtmp://other/live"); 
};

function onStatus(info){   
  switch (info.code) {
    case "NetConnection.Connect.Success" :
      application.myStream = Stream.get("livestream");
      if (application.myStream){
        application.myStream.play("livestream",-2, -1,false,application.myNC);
      }
      break;
    case "NetConnection.Connect.Failed" :
      break;
    case "NetConnection.Connect.Rejected" :
      break;
  }
}
```

**Comment by MathieuPOUX** [comment]
Hi,

I don't understand exactly what are you doing, here replace "other" by the
address of Mona.
ex:  this.myNC.connect("rtmp://localhost/live");

2017-01-06 21:16 GMT+01:00 Dreamszhu <notifications@github.com>:

**Comment by dreamsxin** [comment]
Ex I has publish two stream `rtmp:://localhost/live/one` and `rtmp:://localhost/live/two` , want server switch one publish to `rtmp://localhost/three` , client only play stream three.

**Comment by thomasjammet** [comment]
Ok I understand,

This is quite expensive but you can listen to the onAudio and onVideo publication events (www.monaserver.ovh/api.html#publication) and publish into a new publication. Here is a sample of publishing into a new publication from lua source code : 
https://github.com/MonaSolutions/MonaServer/blob/master/FunctionalTests/www/FunctionalTests/Media/main.lua

(This is a more complex code where we publish a video from a file, in your case you just need to call mona:publish() and publication:pushAudio() & publication:pushVideo())

Regards

**Comment by dreamsxin** [comment]
Think you very much.
