### ISSUE TITLE
security: deny connecting or publishing or getting the stream

### ISSUE THREAD

**Issue by easymind76** [MonaSolutions/MonaServer#45]
I cannot find any way to implement some security because I don't know how to deny someone from connecting or publishing or from reading the stream.
Let's say I want the client to send username and password on the connect call.
I know I can have the client pass those as arguments to the main.lua onConnection function.
But now a way to deny the connection, return maybe and error event or something.

Is there something?

And through the build in http server it is possible for the outside world to read the main.lua files and othe lua files.  How to send 404 if those files are http accessed?

**Comment by thomasjammet** [comment]
Hi,

You're right, you just have to write an error in the onConnection event, see here an example :
http://www.monaserver.ovh/api.html#onconnection-client
And this is the same for onSubscribe or onPublication events (see [client object in the API documentation](http://www.monaserver.ovh/api.html#client)).

About the main.lua yes by default it is possible to read all the files in your directories. What you can do to avoid this is implementing the client:onRead() function (see [client object in the API documentation](http://www.monaserver.ovh/api.html#client)) :

```
function client:onRead(file)
  if file ~= "index.html" then
    error("Access forbidden)
  end
end
```

Regards
