### ISSUE TITLE
IDE for Lua development

### ISSUE THREAD

**Issue by sigaev-pro** [MonaSolutions/MonaServer#46]
Hi!
I'm new for MonaServer and going to develop simple app for it. I'm looking for some comfortable IDE wich may be supported some code completion for MonaServer.
Thank for any advice.

**Comment by MathieuPOUX** [comment]
Hi,

Unfortunatly this kind of tool doesn't exist currently.
On my side I use Notepad++ which supports LUA coloration syntax.
Now LUA langage is full documented on the web, and for special Mona
addition look server application documentation
<http://www.monaserver.ovh/serverapp.html>.

Now if you or your company would like to invest development on this feature
we would be delighted to work together on that (I think to a web-editor to
list server file and allows remoting edition with syntax coloration and
completion).

Best regards,
Mathieu

2017-01-19 23:03 GMT+01:00 Vadim Sigaev <notifications@github.com>:
