### ISSUE TITLE
RTMP blank screen no errors

### ISSUE THREAD

**Issue by dbartholomae** [MonaSolutions/MonaServer#49]
Hi there!

I've installed MonaServer on Windows 10 and now I'm trying to stream from OBS on one computer to OBS on another computer. Handshake and all seems to work (at least I don't get any error messages), but when I look at the stream it is empty. I've tried turning off the firewall or using different players (e. g. VLC) and streaming with something else than OBS (an iPhone app for streaming), but no difference.
Attached are the [logs](https://github.com/MonaSolutions/MonaServer/files/730232/log.zip).

Any ideas what could be the issue here? :)

Best,
Daniel

**Comment by MathieuPOUX** [comment]
Hi,

You have tried to remove /dump argument? :-)
I see in the logs dump on any request, /dump is just a development tool,
and on media streaming real-time with dump is impossible, it can give a
black screen as reported.
Try with a normal MonaServer starts, and let me know.

Best,
Mathieu

2017-01-25 17:13 GMT+01:00 Daniel Bartholomae <notifications@github.com>:

**Comment by dbartholomae** [comment]
Yes, I did - just reran with log level 8 and dump to help debugging :)

**Comment by MathieuPOUX** [comment]
I have just gave a quick look to logs, and it looks that there is a
confusion between "path" and "stream name" in your player usage.
I explain:

> sources\Publication.cpp[87]  Publication laptop started
> sources\Publication.cpp[253]  Write laptop publication properties
> ...
> sources\FlashMainStream.cpp[160]  Method client 'getStreamLength' not
> found in application /laptop


The two first line reflect your publication named "laptop".
The last line shows that you tries to connect your player with a "/laptop"
path and without stream name.
Indeed, if you use some RTMP client like VLC, the usage is to set the
stream name at last element in the path, for example:

*rtmp://localhost/live/laptop*

If you use it rather:

*rtmp://localhost/laptop*

VLC connects to RTMP server to a "laptop" application and tries to play a
stream with empty name.

Now don't forget to create the application associated:

> sources\MonaServer.cpp[484] Application /live doesn't exist


Fix it in creating a folder "live" in your "www" folder.

Best,
Mathieu

2017-01-25 19:55 GMT+01:00 Daniel Bartholomae <notifications@github.com>:

**Comment by dbartholomae** [comment]
Thanks, Mathieu! :)

Now I feel stupid for not having gotten that right :D
Unfortunately I don't know much C++ or Lua, so can't help that way - doyou have PayPal for donations or something like that? :)

Best,
Daniel

**Comment by MathieuPOUX** [comment]
Thanks for your interest, follow Mona in next month because a new complete
version is releasing.
Link for donation
<https://www.paypal.com/us/cgi-bin/webscr?cmd=_flow&SESSION=C0PgP1dhjBH1bP6FRFksNjOgjmCpAuUSbO5Q7m9INY6THjLSgY_SHp_px1W&dispatch=5885d80a13c0db1f8e263663d3faee8d333dc9aadeed3fe0b5b299d55fd35542>
.

Best regards,
Mathieu

2017-01-27 2:20 GMT+01:00 Daniel Bartholomae <notifications@github.com>:
