### ISSUE TITLE
Is there a way to record audio&video stream on mona server using RTMP?

### ISSUE THREAD

**Issue by byrne** [MonaSolutions/MonaServer#5]
It seems this feature is not implemented on Cumulus. How about MonaServer?

**Comment by thomasjammet** [comment]
I wrote a sample of audio&video synchronous recording in the VideoPublisher client, here is the lua code : https://github.com/MonaSolutions/MonaClients/blob/master/VideoPublisher/main.lua

Another possibility is to connect to http://<host address>/<publication name>.flv and record the stream received.
