### ISSUE TITLE
Compiling on AARCH64 ARM 64 Bits

### ISSUE THREAD

**Issue by gdeverlant** [MonaSolutions/MonaServer#54]
I get lots of errors when I try to build MonaServer with make on arm64.

**Comment by gdeverlant** [comment]
Makefile:47: recipe for target 'tmp/Release/Application.o' failed
make[2]: *** [tmp/Release/Application.o] Error 1
compiling sources/Util.cpp
In file included from ./include/Mona/Util.h:22:0,
                 from sources/Util.cpp:20:
./include/Mona/Mona.h:214:2: error: #error "Unknown Hardware Architecture."
 #error "Unknown Hardware Architecture."
  ^
Makefile:47: recipe for target 'tmp/Release/Util.o' failed
make[2]: *** [tmp/Release/Util.o] Error 1
compiling sources/Option.cpp
In file included from ./include/Mona/Option.h:22:0,
                 from sources/Option.cpp:20:
./include/Mona/Mona.h:214:2: error: #error "Unknown Hardware Architecture."
 #error "Unknown Hardware Architecture."
  ^
Makefile:47: recipe for target 'tmp/Release/Option.o' failed
make[2]: *** [tmp/Release/Option.o] Error 1
make[2]: Leaving directory '/mnt/virtual/MonaServer/MonaBase'
Makefile:29: recipe for target 'release' failed
make[1]: *** [release] Error 2
make[1]: Leaving directory '/mnt/virtual/MonaServer/MonaBase'
Makefile:2: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by thomasjammet** [comment]
Hi,

This is a normal error, we have never tried to compile with this architecture.
I have made an update to Mona, can you tell me if it is compiling now?

Thank you

**Comment by gdeverlant** [comment]
So far so good it's compiling well!

**Comment by gdeverlant** [comment]
make[2]: Entering directory '/mnt/virtual/MonaServer/MonaServer'
compiling sources/LUAClient.cpp
In file included from sources/LUAClient.h:23:0,
                 from sources/LUAClient.cpp:20:
sources/Script.h:27:29: fatal error: luajit-2.0/lua.h: No such file or directory
  #include "luajit-2.0/lua.h"
                             ^
compilation terminated.
Makefile:45: recipe for target 'tmp/Release/LUAClient.o' failed
make[2]: *** [tmp/Release/LUAClient.o] Error 1
compiling sources/MonaServer.cpp
In file included from sources/Service.h:23:0,
                 from sources/MonaServer.h:25,
                 from sources/MonaServer.cpp:20:
sources/Script.h:27:29: fatal error: luajit-2.0/lua.h: No such file or directory
  #include "luajit-2.0/lua.h"
                             ^
compilation terminated.
Makefile:45: recipe for target 'tmp/Release/MonaServer.o' failed
make[2]: *** [tmp/Release/MonaServer.o] Error 1
compiling sources/LUAXML.cpp
In file included from sources/LUAXML.h:23:0,
                 from sources/LUAXML.cpp:20:
sources/Script.h:27:29: fatal error: luajit-2.0/lua.h: No such file or directory
  #include "luajit-2.0/lua.h"

**Comment by gdeverlant** [comment]
I just tried this  sudo apt-get install luajit

**Comment by thomasjammet** [comment]
Have you followed the [luajit installation instructions](http://www.monaserver.ovh/installation.html#luajit-installation)? It is better to follow this paragraph to have every features working well. 

Though you could install luajit-devel if you don't care about lua 52 facilities (pairs() & ipairs() for example, see [this article](http://luajit.org/extensions.html) for further information).

**Comment by gdeverlant** [comment]
==== Building LuaJIT 2.0.4 ====
make -C src
make[1]: Entering directory '/mnt/virtual/luajit-2.0/src'
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^
lj_arch.h:294:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^
lj_arch.h:294:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^
lj_arch.h:294:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^
lj_arch.h:294:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^
lj_arch.h:294:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^
lj_arch.h:294:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^
Makefile:254: *** Unsupported target architecture.  Stop.
make[1]: Leaving directory '/mnt/virtual/luajit-2.0/src'
Makefile:109: recipe for target 'src/luajit' failed
make: *** [src/luajit] Error 2

**Comment by gdeverlant** [comment]
There is no 

Then set the DLUAJIT_ENABLE_LUA52COMPAT option :
On Linux just search DLUAJIT_ENABLE_LUA52COMPAT in src/Makefile and uncomment the line
On Windows search the line beginning with @set LJCOMPILE=cl /nologo /c /O2 /W3 /D_CRT_SECURE_NO_DEPRECATE in src/msvcbuild.bat. Then add the /DLUAJIT_ENABLE_LUA52COMPAT option

in the Makefile

**Comment by gdeverlant** [comment]
I'm trying with this https://github.com/cbaylis/luajit-aarch64.git

**Comment by gdeverlant** [comment]
No it doesn't work at all that's sadddddd

**Comment by thomasjammet** [comment]
Ok I see the problem.

According to [this link](https://fosdem.org/2017/schedule/event/luajit/) luajit 2.0 is not supporting aarch64 but you can try with branch [luajit 2.1](http://repo.or.cz/luajit-2.0.git/shortlog/refs/heads/v2.1).

In luajit 2.0 you will find the line with LUA52COMPAT there : http://repo.or.cz/luajit-2.0.git/blob/refs/heads/master:/src/Makefile#l105

By the way you could work with MonaTiny ([MonaServer2](https://github.com/MonaSolutions/MonaServer2)) if you don't need to write server applications. It is the next version of MonaServer with some improvements but without lua support for now.

I hope it will resolve your problem. It is a good thing if we can add support to aarch64.

**Comment by gdeverlant** [comment]
I would love to be able to use MonaServer2 what are the features I can't use from MonaServer1 ????

**Comment by gdeverlant** [comment]
Ok I've done Lua JIT 2.1 beta

CC        lib_table.o
CC        lib_io.o
CC        lib_os.o
CC        lib_package.o
CC        lib_debug.o
CC        lib_jit.o
CC        lib_ffi.o
CC        lib_init.o
AR        libluajit.a
CC        luajit.o
BUILDVM   jit/vmdef.lua
DYNLINK   libluajit.so
LINK      luajit
OK        Successfully built LuaJIT
make[1]: Leaving directory '/mnt/virtual/LuaJIT/src'
==== Successfully built LuaJIT 2.1.0-beta2 ====
==== Installing LuaJIT 2.1.0-beta2 to /usr/local ====
mkdir -p /usr/local/bin /usr/local/lib /usr/local/include/luajit-2.1 /usr/local/share/man/man1 /usr/local/lib/pkgconfig /usr/local/share/luajit-2.1.0-beta2/jit /usr/local/share/lua/5.1 /usr/local/lib/lua/5.1

==== Installing LuaJIT 2.1.0-beta2 to /usr/local ====
mkdir -p /usr/local/bin /usr/local/lib /usr/local/include/luajit-2.1 /usr/local/share/man/man1 /usr/local/lib/pkgconfig /usr/local/share/luajit-2.1.0-beta2/jit /usr/local/share/lua/5.1 /usr/local/lib/lua/5.1
cd src && install -m 0755 luajit /usr/local/bin/luajit-2.1.0-beta2
cd src && test -f libluajit.a && install -m 0644 libluajit.a /usr/local/lib/libluajit-5.1.a || :
rm -f /usr/local/lib/libluajit-5.1.so.2.1.0 /usr/local/lib/libluajit-5.1.so /usr/local/lib/libluajit-5.1.so.2
cd src && test -f libluajit.so && \
  install -m 0755 libluajit.so /usr/local/lib/libluajit-5.1.so.2.1.0 && \
  ldconfig -n /usr/local/lib && \
  ln -sf libluajit-5.1.so.2.1.0 /usr/local/lib/libluajit-5.1.so && \
  ln -sf libluajit-5.1.so.2.1.0 /usr/local/lib/libluajit-5.1.so.2 || :
cd etc && install -m 0644 luajit.1 /usr/local/share/man/man1
cd etc && sed -e "s|^prefix=.*|prefix=/usr/local|" -e "s|^multilib=.*|multilib=lib|" luajit.pc > luajit.pc.tmp && \
  install -m 0644 luajit.pc.tmp /usr/local/lib/pkgconfig/luajit.pc && \
  rm -f luajit.pc.tmp
cd src && install -m 0644 lua.h lualib.h lauxlib.h luaconf.h lua.hpp luajit.h /usr/local/include/luajit-2.1
cd src/jit && install -m 0644 bc.lua bcsave.lua dump.lua p.lua v.lua zone.lua dis_x86.lua dis_x64.lua dis_arm.lua dis_arm64.lua dis_arm64be.lua dis_ppc.lua dis_mips.lua dis_mipsel.lua dis_mips64.lua dis_mips64el.lua vmdef.lua /usr/local/share/luajit-2.1.0-beta2/jit
==== Successfully installed LuaJIT 2.1.0-beta2 to /usr/local ====

Note: the development releases deliberately do NOT install a symlink for luajit
You can do this now by running this command (with sudo):

  ln -sf luajit-2.1.0-beta2 /usr/local/bin/luajit

**Comment by gdeverlant** [comment]
But still it doesn't compile

$ make
cd MonaBase && make && cd ../MonaCore && make && cd ../MonaServer && make && cd ../UnitTests && make
make[1]: Entering directory '/mnt/virtual/MonaServer/MonaBase'
mkdir -p tmp/Release
mkdir -p lib
make[2]: Entering directory '/mnt/virtual/MonaServer/MonaBase'
make[2]: 'tmp/Release/IPAddress.o' is up to date.
make[2]: 'tmp/Release/HostEntry.o' is up to date.
make[2]: 'tmp/Release/Trigger.o' is up to date.
make[2]: 'tmp/Release/UDPSocket.o' is up to date.
make[2]: 'tmp/Release/Options.o' is up to date.
make[2]: 'tmp/Release/PersistentData.o' is up to date.
make[2]: 'tmp/Release/DiffieHellman.o' is up to date.
make[2]: 'tmp/Release/Logs.o' is up to date.
make[2]: 'tmp/Release/TaskHandler.o' is up to date.
make[2]: 'tmp/Release/AttemptCounter.o' is up to date.
make[2]: 'tmp/Release/Task.o' is up to date.
make[2]: 'tmp/Release/TCPServer.o' is up to date.
make[2]: 'tmp/Release/ServerApplication.o' is up to date.
make[2]: 'tmp/Release/Startable.o' is up to date.
make[2]: 'tmp/Release/QualityOfService.o' is up to date.
make[2]: 'tmp/Release/Parameters.o' is up to date.
make[2]: 'tmp/Release/Logger.o' is up to date.
make[2]: 'tmp/Release/Date.o' is up to date.
make[2]: 'tmp/Release/String.o' is up to date.
make[2]: 'tmp/Release/FileSystem.o' is up to date.
make[2]: 'tmp/Release/PoolBuffers.o' is up to date.
make[2]: 'tmp/Release/SocketManager.o' is up to date.
make[2]: 'tmp/Release/Net.o' is up to date.
make[2]: 'tmp/Release/Socket.o' is up to date.
make[2]: 'tmp/Release/MapParameters.o' is up to date.
make[2]: 'tmp/Release/SubstreamMap.o' is up to date.
make[2]: 'tmp/Release/Crypto.o' is up to date.
make[2]: 'tmp/Release/TerminateSignal.o' is up to date.
make[2]: 'tmp/Release/File.o' is up to date.
make[2]: 'tmp/Release/BinaryWriter.o' is up to date.
make[2]: 'tmp/Release/PoolThread.o' is up to date.
make[2]: 'tmp/Release/Exceptions.o' is up to date.
make[2]: 'tmp/Release/XMLParser.o' is up to date.
make[2]: 'tmp/Release/BinaryReader.o' is up to date.
make[2]: 'tmp/Release/FileWatcher.o' is up to date.
make[2]: 'tmp/Release/SocketAddress.o' is up to date.
make[2]: 'tmp/Release/SocketSender.o' is up to date.
make[2]: 'tmp/Release/HelpFormatter.o' is up to date.
make[2]: 'tmp/Release/TCPClient.o' is up to date.
make[2]: 'tmp/Release/Signal.o' is up to date.
make[2]: 'tmp/Release/Timezone.o' is up to date.
make[2]: 'tmp/Release/Mona.o' is up to date.
make[2]: 'tmp/Release/Process.o' is up to date.
make[2]: 'tmp/Release/Buffer.o' is up to date.
make[2]: 'tmp/Release/DNS.o' is up to date.
make[2]: 'tmp/Release/Application.o' is up to date.
make[2]: 'tmp/Release/Util.o' is up to date.
make[2]: 'tmp/Release/Option.o' is up to date.
make[2]: Leaving directory '/mnt/virtual/MonaServer/MonaBase'
creating dynamic lib lib/libMonaBase.so
creating static lib lib/libMonaBase.ar
make[1]: Leaving directory '/mnt/virtual/MonaServer/MonaBase'
make[1]: Entering directory '/mnt/virtual/MonaServer/MonaCore'
mkdir -p tmp/Release
mkdir -p lib
make[2]: Entering directory '/mnt/virtual/MonaServer/MonaCore'
make[2]: 'tmp/Release/Listener.o' is up to date.
make[2]: 'tmp/Release/Server.o' is up to date.
make[2]: 'tmp/Release/AMFWriter.o' is up to date.
make[2]: 'tmp/Release/XMLRPCReader.o' is up to date.
make[2]: 'tmp/Release/FlashStream.o' is up to date.
make[2]: 'tmp/Release/JSONReader.o' is up to date.
make[2]: 'tmp/Release/Peer.o' is up to date.
make[2]: 'tmp/Release/DataReader.o' is up to date.
make[2]: 'tmp/Release/ICE.o' is up to date.
make[2]: 'tmp/Release/MIME.o' is up to date.
make[2]: 'tmp/Release/SDP.o' is up to date.
make[2]: 'tmp/Release/Session.o' is up to date.
make[2]: 'tmp/Release/RelayServer.o' is up to date.
make[2]: 'tmp/Release/Sessions.o' is up to date.
make[2]: 'tmp/Release/Protocols.o' is up to date.
make[2]: 'tmp/Release/AMFReader.o' is up to date.
make[2]: 'tmp/Release/TCPSession.o' is up to date.
make[2]: 'tmp/Release/XMLRPCWriter.o' is up to date.
make[2]: 'tmp/Release/Writer.o' is up to date.
make[2]: 'tmp/Release/ReferableReader.o' is up to date.
make[2]: 'tmp/Release/Invoker.o' is up to date.
make[2]: 'tmp/Release/Publication.o' is up to date.
make[2]: 'tmp/Release/MediaContainer.o' is up to date.
make[2]: 'tmp/Release/QueryReader.o' is up to date.
make[2]: 'tmp/Release/FlashWriter.o' is up to date.
make[2]: 'tmp/Release/QueryWriter.o' is up to date.
make[2]: 'tmp/Release/FlashMainStream.o' is up to date.
make[2]: 'tmp/Release/JSONWriter.o' is up to date.
make[2]: 'tmp/Release/RTMFPCookie.o' is up to date.
make[2]: 'tmp/Release/RTMFPCookieComputing.o' is up to date.
make[2]: 'tmp/Release/RTMFPFlow.o' is up to date.
make[2]: 'tmp/Release/RTMFP.o' is up to date.
make[2]: 'tmp/Release/RTMFPSender.o' is up to date.
make[2]: 'tmp/Release/RTMFPHandshake.o' is up to date.
make[2]: 'tmp/Release/RTMFPSession.o' is up to date.
make[2]: 'tmp/Release/RTMFPWriter.o' is up to date.
make[2]: 'tmp/Release/RTMFPDecoder.o' is up to date.
make[2]: 'tmp/Release/RTMFProtocol.o' is up to date.
make[2]: 'tmp/Release/HTTPDecoder.o' is up to date.
make[2]: 'tmp/Release/HTTPPacket.o' is up to date.
make[2]: 'tmp/Release/HTTPSession.o' is up to date.
make[2]: 'tmp/Release/HTTPWriter.o' is up to date.
make[2]: 'tmp/Release/HTTPSender.o' is up to date.
make[2]: 'tmp/Release/HTTP.o' is up to date.
make[2]: 'tmp/Release/RTSPPacket.o' is up to date.
make[2]: 'tmp/Release/RTSPSession.o' is up to date.
make[2]: 'tmp/Release/RTSPWriter.o' is up to date.
make[2]: 'tmp/Release/RTSPSender.o' is up to date.
make[2]: 'tmp/Release/RTSP.o' is up to date.
make[2]: 'tmp/Release/RTMPHandshaker.o' is up to date.
make[2]: 'tmp/Release/RTMP.o' is up to date.
make[2]: 'tmp/Release/RTMPSession.o' is up to date.
make[2]: 'tmp/Release/RTMPSender.o' is up to date.
make[2]: 'tmp/Release/RTMPWriter.o' is up to date.
make[2]: 'tmp/Release/WS.o' is up to date.
make[2]: 'tmp/Release/WSDecoder.o' is up to date.
make[2]: 'tmp/Release/WSWriter.o' is up to date.
make[2]: 'tmp/Release/WSSession.o' is up to date.
make[2]: Leaving directory '/mnt/virtual/MonaServer/MonaCore'
creating dynamic lib lib/libMonaCore.so
make[1]: Leaving directory '/mnt/virtual/MonaServer/MonaCore'
make[1]: Entering directory '/mnt/virtual/MonaServer/MonaServer'
mkdir -p tmp/Release/
make[2]: Entering directory '/mnt/virtual/MonaServer/MonaServer'
compiling sources/LUAClient.cpp
In file included from sources/LUAClient.h:23:0,
                 from sources/LUAClient.cpp:20:
sources/Script.h:27:29: fatal error: luajit-2.0/lua.h: No such file or directory
  #include "luajit-2.0/lua.h"
                             ^
compilation terminated.
Makefile:45: recipe for target 'tmp/Release/LUAClient.o' failed

**Comment by gdeverlant** [comment]
Can you do something that MonaServer1 uses LuaJIT 2.1.0 beta instead of 2.0 ?

**Comment by gdeverlant** [comment]
Wait I changed this 

extern "C" {
	#include "luajit-2.0/lua.h"
	#include "luajit-2.0/lauxlib.h"
}

to 

extern "C" {
	#include "luajit-2.1/lua.h"
	#include "luajit-2.1/lauxlib.h"
}

**Comment by gdeverlant** [comment]
HOURRRAAAYYYYYYYY I've made it work on ARM64!!!!!!

**Comment by thomasjammet** [comment]
Great!

Ok, you can change the luajit-2.0 inclusion like you did or create a symlink like this : 
ln -s /usr/include/luajit-2.1 /usr/include/luajit-2.0

MonaServer2 don't have support for lua and do not have a cache system (NoSQL database). It is the simplest implementation of a media server. But is has congestion control, support for SSL, recording and other features that will be documented ASAP.

**Comment by gdeverlant** [comment]
Thomas c'est une des raisons pourquoi j'adore Mona... c'est hyper simple de tout faire... meme la compil...

Mathieu et toi vous faites une bonne paire.... Mes salutations a Mathieu !

**Comment by gdeverlant** [comment]
Can you tell me in terms of % how much of the basic functionalities are implemented in MonaServer2

What I'm most interested in is RTMFP and RTMP

**Comment by thomasjammet** [comment]
RTMFP and RTMP are fully implemented in MonaServer2. In fact every updates are only made to MonaServer2 so it is the most updated server.

Now you cannot use the [lua API](http://www.monaserver.ovh/api.html) in MonaServer2 for now. If you need to customize MonaServer2 and add your own API you should implement it into MonaTiny in C++ (and share the source code or buy a license). I hope we will find soon some founds to add support for lua and the cache system to MonaServer2.
