### ISSUE TITLE
not display video streaming with rtmfp

### ISSUE THREAD

**Issue by aazjcom** [MonaSolutions/MonaServer#55]
i use rtmfp . two clients can connect server,but they are not display video streaming .i think they can not connect each other.
like this https://forums.adobe.com/message/6901683#6901683.[https://forums.adobe.com/message/6901683#6901683](url)

**Comment by aazjcom** [comment]
one client is vpn

**Comment by thomasjammet** [comment]
Hi,

Yes the P2P is not guaranteed if the peers are behind a symmetric NAT. Can you tell me the result of http://cc.rtmfp.net/ on each of your computers? 

An other possibility is that one of the client is behind the same NAT as the server, it could not work too.

**Comment by aazjcom** [comment]
thank you .can google webctr solve it?

**Comment by thomasjammet** [comment]
I guess you mean WebRTC, and no I don't think so but some solutions are possible to correct this with some development. Though it will never be possible to have 100% of P2P connections working.

**Comment by gdeverlant** [comment]
Why is Mona not supporting something like RTMPT tunneling over port 80
With this feature there is no firewall problem.

On Wikipedia 

RTMPT, which is encapsulated within HTTP requests to traverse firewalls. RTMPT is frequently found utilizing cleartext requests on TCP ports 80 and 443 to bypass most corporate traffic filtering. The encapsulated session may carry plain RTMP, RTMPS, or RTMPE packets within.

**Comment by thomasjammet** [comment]
Yes we know well RTMPT, it is not helpful in this case because we are talking about P2P.
Though it will be great to implement RTMPT, we just need someone to pay for it ;)

**Comment by aazjcom** [comment]
is there a tool to test p2p?i need 100 clients with video,but i have not so much laptops.

**Comment by thomasjammet** [comment]
For testing p2p availability on a computer there is an online tool here : http://cc.rtmfp.net/

**Comment by aazjcom** [comment]
thank everyone, i have gaven up  adobe.
