### ISSUE TITLE
[Q] Remove stream buffer

### ISSUE THREAD

**Issue by alekthefirst** [MonaSolutions/MonaServer#74]
Every time i connect clients to monaserver this line pops up.

sources\FlashStream.cpp[112] setBufferTime 3000ms on steam 1.

Then i also notice that the delay from capture on computer 1 to view on computer 2 is approximately 3 seconds.

So is it possible to set the BufferTime variable to 0ms or disable it some other way to make the stream almost immidiate?

**Comment by MathieuPOUX** [comment]
The server displays just what is doing the client (here a [NetStream.bufferTime](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/NetStream.html#bufferTime) = 3000) but don't bufferize anything (the live stream is always transferring immediatly), it's the client here which bufferizes its stream before to displays it.
I don't know what is the client that you are using and if you have handle on that, but the alone way where you can change it is on client side.

**Comment by alekthefirst** [comment]
> I don't know what is the client that you are using and if you have handle on that

VLC connecting to monaserver using monaclients with /VideoPlayer/?unbuffered&?unreliable&?bufMax=0

**Comment by MathieuPOUX** [comment]
And yes I see and know it with VLC and RTMP, I have never understood why VLC configure a such buffering delay on client side for RTMP and I have never found a configuration in VLC to fix it. All the configuration that you pass to Mona acts just on server side, but Mona bufferizes already nothing and relays just packet to VLC.
With VLC I have observed that in HTTP/TS VLC buffering is more live, try to play in VLC "http://mona-address/nameStream.ts", or use a live RTMP player (this [player](https://www.hlsplayer.net/rtmp-player) for example set buffer playing to 100ms), or code your own AS3 player in setting netStream.bufferTime to 0.
