### ISSUE TITLE
Issue when i compilate MonaServer on debian

### ISSUE THREAD

**Issue by triseaux** [MonaSolutions/MonaServer#78]
Hi, anyone can helpp me pleas ?
When i make an make for build MonaServer i have lot of error.

gcc-6 installed
LuaJit installed
OpenSSL (libssl-dev) installed

`./include/Mona/Exceptions.h:114:157: warning: throw will always call terminate() [-Wterminate]
  #define  FATAL_ERROR(...)     {std::string __error; throw std::runtime_error(Mona::String::Format(__error,## __VA_ARGS__,", " __FILE__ "[" LINE_STRING "]"));}
                                                                                                                                                             ^
./include/Mona/Event.h:102:4: note: in expansion of macro âFATAL_ERRORâ
    FATAL_ERROR("Deleting function during event ", typeid(*this).name()," subscription");
    ^~~~~~~~~~~
./include/Mona/Exceptions.h:114:157: note: in C++11 destructors default to noexcept
  #define  FATAL_ERROR(...)     {std::string __error; throw std::runtime_error(Mona::String::Format(__error,## __VA_ARGS__,", " __FILE__ "[" LINE_STRING "]"));}
                                                                                                                                                             ^
./include/Mona/Event.h:102:4: note: in expansion of macro âFATAL_ERRORâ
    FATAL_ERROR("Deleting function during event ", typeid(*this).name()," subscription");
    ^~~~~~~~~~~
./include/Mona/Event.h: In instantiation of âMona::Event<Result, ArgsType>::~Event() [with Result = void; ArgsType = {}]â:
./include/Mona/Event.h:127:7:   required from here
./include/Mona/Exceptions.h:114:157: warning: throw will always call terminate() [-Wterminate]
  #define  FATAL_ERROR(...)     {std::string __error; throw std::runtime_error(Mona::String::Format(__error,## __VA_ARGS__,", " __FILE__ "[" LINE_STRING "]"));}
                                                                                                                                                             ^
./include/Mona/Event.h:102:4: note: in expansion of macro âFATAL_ERRORâ
    FATAL_ERROR("Deleting function during event ", typeid(*this).name()," subscription");
    ^~~~~~~~~~~
./include/Mona/Exceptions.h:114:157: note: in C++11 destructors default to noexcept
  #define  FATAL_ERROR(...)     {std::string __error; throw std::runtime_error(Mona::String::Format(__error,## __VA_ARGS__,", " __FILE__ "[" LINE_STRING "]"));}
`

Thx for help

**Comment by MathieuPOUX** [comment]
Can you type "g++ -v" and paste here the exact result?
Then I don't see "error" but "warning" in what do you share?

**Comment by triseaux** [comment]
Hey, thx for help,

`Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
`

Finaly when wait is compiling but lots of warnings ....
Its not a problem ?

**Comment by MathieuPOUX** [comment]
Yes, I see,
Indeed, it's not an issue, it's a new warning added since g++6 which is not relevant for Mona since Mona uses its own exception system.
I have [fixed it just now](https://github.com/MonaSolutions/MonaServer/commit/b03f6c5c66226aecfffc226dc36fb9e4b74489a8) in makefile to ignore it, thanks!
