### ISSUE TITLE
ffplay rtmp stream, the MonaTiny core dump

### ISSUE THREAD

**Issue by halivor** [MonaSolutions/MonaServer#79]
Hi, when I use the latest MonaTiny, I meet a problem
1. I push a live stream to the server
ffmpeg -probesize 32 -analyzeduration 0 -i https://domain.com/stream.flv -vf scale=640x720 -c:a aac -ar 22050 -c:v h264 -r 15 -g 15 -f flv rtmp://127.0.0.1/mic/1000
2. I use ffplay to play the stream
ffplay rtmp://10.20.6.51/mic/1000

then receive the fault
MonaTiny: sources/Application.cpp:59: Assertion `Segmentation violation' failed.

here's the backtrace
![1](https://user-images.githubusercontent.com/7335476/43136352-09843886-8f7b-11e8-990a-e6c84efa3f01.jpg)
![2](https://user-images.githubusercontent.com/7335476/43136353-09b78ae2-8f7b-11e8-8eb2-5b0b4cdacd9d.jpg)

**Comment by thomasjammet** [comment]
Hi, 

Thanks for the report, I think this is resolved in the current version, could you update and try again?

Thanks

**Comment by halivor** [comment]
Yes, it's ok now.
Thanks
