### ISSUE TITLE
What about rtmfp performance？

### ISSUE THREAD

**Issue by kingyiren** [MonaSolutions/MonaServer#8]
for example :+1: 
 10000 concurrent connection / one Server？

is there any docment about MonaServer‘s rtmfp performance？

BTW，I have no idea to test rtmfp！！！I had tested it by flash client，，，
but only less than 2000 connections is running，and I need to verify that more than 100000 rtmfp connections can be running！

thanks.

**Comment by thomasjammet** [comment]
Hi kingyiren,

You could not handle 100000 on a unique server for a simple reason : there are only 65535 ports and some are reserved. Now it also depends on your server memory/power.

I encourage you to take a look at the [Scalability](http://www.monaserver.ovh/scalability.html) page in our documentation to know how to configure many instances of MonaServer running together.

In your case have you tried to run many instances of your flash client connecting to MonaServer? I think that 2000 connections is less than our capabilities, MonaServer should handle more than that.

Sadly there is no benchmark of MonaServer so if some volunteer is interested, it could be interesting for other users.

I hope it will help

**Comment by arpu** [comment]
Hi 

Load balancing and rendezvous service does not work since some month, i do not remeber the exact 
commit, i told this Mathieu.

the Problem i remember is 
mona.servers:broadcast(..) 

best regards

**Comment by arpu** [comment]
here is the error
www/main.lua[53] (metamethod '__index') Cast error, type 0x4d1e20 doesn't match 0x4c4b80 of 11Broadcaster type
sources/MonaServer.cpp[819] ...MonaServer_20.10.2014/MonaServer/MonaServer/www/main.lua:53: attempt to call method 'broadcast' (a nil value)



        function client:onUnjoinGroup(group)
                -- inform other servers of this unjoining operation
                mona.servers:broadcast("unjoin",group.rawId,self.rawId)
        end
