### ISSUE TITLE
Cannot get it working anymore, missing something simple!

### ISSUE THREAD

**Issue by maffbm** [MonaSolutions/MonaServer#82]
I used to have this working fine before I had to re-install Windows.  I have port 1935 forwarded to my PC on my router. I have been reading & watching tutorials, but I'm now stuck.
I have downloaded Mona server, run it so it created a www folder for me, in there I have added a folder called 'test', closed & re-run mona server.
The window has:
```
Mona/Protocols.h[102] RTMFP server started on 0.0.0.0:1935 (UDP)
Mona/Protocols.h[102] RTMP server started on 0.0.0.0:1935 (TCP)
Mona/Protocols.h[102] HTTP server started on 0.0.0.0:80 (TCP)
Mona/Protocols.h[102] RTSP server started on 0.0.0.0:554 (TCP)
```
In OBS (same PC), I have set stream URL to rtmp://127.0.0.1 and stream key to 'test', clicked "start streaming" which gives readout like this:
```
20/09 09:25:45.8  ERROR	Server(12128)	sources\FlashMainStream.cpp[160]  Method 'releaseStream' not found on application 
20/09 09:25:45.8  ERROR	Server(12128)	sources\FlashMainStream.cpp[160]  Method 'FCPublish' not found on application 
20/09 09:25:45.8  INFO	Server(12128)	sources\Publication.cpp[87]  Publication test started
20/09 09:25:45.8  WARN	Server(12128)	sources\AMFWriter.cpp[228]  Mixed object in AMF0 are not supported, switch to AMF3
20/09 09:25:45.8  INFO	Server(12128)	sources\Publication.cpp[253]  Write test publication properties
20/09 09:25:47.7  NOTE	Server(12128)	RTMP\RTMPSession.cpp[279]  Sending ACK : 134514 bytes (_unackBytes: 134514)
20/09 09:25:47.7  INFO	Server(12128)	sources\Server.cpp[144]  1 clients
```
Then in VLC, on my phone (4G) I try to connect to: rtmp://<servername>/test, or, rtmp://127.0.0.1/test on my PC, the log then says:
```
20/09 09:28:26.4  ERROR	Server(8440)	sources\FlashMainStream.cpp[160]  Method 'getStreamLength' not found on application /test
20/09 09:28:26.4  INFO	Server(8440)	sources\FlashStream.cpp[112]  setBufferTime 3000ms on stream 1
20/09 09:28:26.7  NOTE	Server(8440)	RTMP\RTMPSession.cpp[279]  Sending ACK : 1063982 bytes (_unackBytes: 134985)
20/09 09:28:27.1  NOTE	Server(8440)	RTMP\RTMPSession.cpp[279]  Sending ACK : 1197039 bytes (_unackBytes: 133057)
20/09 09:28:27.4  INFO	Server(8440)	sources\Server.cpp[144]  2 clients
```
I know it's something simple that I've figured out before, but I cannot remember what it is!
Can anyone assist?

Thank you
[log.txt](https://github.com/MonaSolutions/MonaServer/files/2400435/log.txt)

**Comment by thomasjammet** [comment]
Hi maffbm,

Just create a new directory in the "www" directory of MonaServer (like "www/live" for example) and when you connect from vlc or another player add this directory in your url (for example "rtmp://localhost/live/test").
librtmp and ffmpeg add this constraint (to add an application/directory) for publishing or playing a stream, this is not true for flash, for example you can play your stream with VideoPlayer using this url : http://raspi.monaserver.ovh/MonaClients/VideoPlayer/?fit&url=rtmp://localhost/test

Also do you know that we are working on [MonaServer2](https://github.com/MonaSolutions/MonaServer2)? There are a lot of new features like http live streaming (you can now publish and play using http), mp4 and ts support, publishing from a movie file, recording etc...
This project will replace MonaServer as soon as we add lua support (for now we cannot focus on this but it will be our priority when we have time).

**Comment by maffbm** [comment]
Thank you v much, the bit about rtmp://server/directory/key always seems to be missing from tutorials or badly worded.
Http live streaming is just what I'm after, I will look into MonaSever2, thanks for the info!
