### ISSUE TITLE
OS-X 10.10.2 Support? LLVM or GCC?

### ISSUE THREAD

**Issue by sushihangover** [MonaSolutions/MonaServer#9]
OS-X 10.10.2 / Apple LLVM version 6.0 / x86_64-apple-darwin14.1.0

I'm assuming from the number of deprecated OS-X function calls and function return errors like "const char *' with an rvalue of type 'bool'" llvm is not supported on OS-X as the compiler.

Are you using GCC to compile MonaServer on OS-X? And if so, which version/libraries?

Thanks in advance.

**Comment by thomasjammet** [comment]
Hi,

Yes, as it is said in http://www.monaserver.ovh/installation.html#dependencies-and-requirements you need at least gcc 4.8.2 to build MonaServer on Linux, FreeBSD and OSX systems.

Sadly we do not have an OS-X system for testing so let us know if you encounter some problems.

**Comment by rubytastic** [comment]
Trying to compile this also on the latest OSX.

Please provide some details on how to get this compiled. 
Would be highly wanted for local debugging purposes.

I tried installing gcc 4.9 with brew but it failed with a 

./gcc-4.9 /users/me/Desktop/monaserver/Makefile 
ld: warning: ignoring file /users/me/Desktop/monaserver/Makefile, file was built for unsupported file format ( 0x72 0x65 0x6C 0x65 0x61 0x73 0x65 0x3A 0x0A 0x09 0x63 0x64 0x20 0x4D 0x6F 0x6E ) which is not the architecture being linked (x86_64): /users/elabbs/Desktop/monaserver/Makefile
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status

Seems its not compatible at all in its current form to be compiled on OSX, @thomasjammet , please see if you can provide a fix for us osx users ;) thank you!

**Comment by thomasjammet** [comment]
hmm, it's me or you are trying to compile the Makefile with gcc?

Just run the Makefile using the command make :

$>make

*--*

*Thomas JAMMET*
Freelancer - MonaServer.ovh
2 Rue Mila - 82000 Montauban (France)
Tel : *+336 23 46 39 80*
http://fr.linkedin.com/pub/thomas-jammet/5a/411/60b/

2015-02-17 14:10 GMT+01:00 rubytastic <notifications@github.com>:

**Comment by rubytastic** [comment]
Compiling it on OSX has all kinds of issues, hope we can resolve these:

Please see attached the full output of the compile:

https://gist.github.com/rubytastic/5df5a0130fa1b0d9986a

**Comment by thomasjammet** [comment]
Ok, could you please confirm your g++ version using the following command : 
```
g++ --version
```

**Comment by rubytastic** [comment]
Its using my OSX default version 4.2.1

Thats the reason I tried to upgrade it to 4.9 but its still using the wrong version. 
My fault. I look into this further, local problem.

**Comment by thomasjammet** [comment]
np,

Maybe try to replace the alias of g++ directly.

*--*

*Thomas JAMMET*
Freelancer - MonaServer.ovh
2 Rue Mila - 82000 Montauban (France)
Tel : *+336 23 46 39 80*
http://fr.linkedin.com/pub/thomas-jammet/5a/411/60b/

2015-02-17 16:26 GMT+01:00 rubytastic <notifications@github.com>:

**Comment by sushihangover** [comment]
Thanks for the info and install link. I did read it, saw the C+11 requirement, but it does not **directly** call out gcc for OS-X, just GCC for Linux, so I assumed clang/llvm would be ok since it is [C+11 compliant](http://clang.llvm.org/cxx_status.html) (-std=c++11 -std=c++1y)...

>As C++11 is used in MonaServer you need to install a compiler which is compatible. At least gcc 4.8.2 on Linux and VS 2013 on Windows.

Maybe update your installation page and say OS-X also requires GCC. Here are my steps (all unit tests passing, but I have not used it real-world yet). PS: If I had a spare Mac available, I'd send it to you... maybe if I can finish this project and get paid, I'll help get you a OS-X dev box...

## My OS-X build steps for MonoServer

	* OS-X Darwin Kernel Version 14.1.0 (10.10.2)
	* g++-4.9 (Homebrew gcc 4.9.2_1) 4.9.2
	* GNU Make 3.81

Install gcc via Homebrew, what not using Homebrew? Then you are doing package management on OS-X all wrong ;-) 

	brew install gcc

*Mac ports works fine also, just install gcc and use gcc_select to switch between the gcc versions*

Update your path to include the brew'd version of gcc/g++. Not sure of the bin directory of your brew installed GCC? Use **brew info gcc** to obtain, don't forget to add 'bin' subdirectory at the end.

	export PATH=$**GCCBrewLinkLocation**/bin:$PATH

`Do whatever cloning/stashing/updating git stuff you need for MonoServer if you have not done so already...`

	 git clone https://github.com/MonaSolutions/MonaServer.git
	 cd MonoServer
	 git stash
	 git fetch --all
	 git checkout master

Clean, make and test MonaServer; the g++ binary name you are passing to **make** would need to be changed based on the gcc version you are currently using.

	cd MonoServer
	make CC=g++-4.9 clean
	make CC=g++-4.9
	cd UnitTests
	./UnitTests -module=all

A multi-part gist of the clean, make and UnitTest output:
[https://gist.github.com/sushihangover/fdc71fd407a338c74ef9](https://gist.github.com/sushihangover/fdc71fd407a338c74ef9)

**Comment by thomasjammet** [comment]
Thank you for your building infos shushihangover, I will update the installation steps.

Good idea for the spare Mac, I hope to have news from you soon! ;)

**Comment by rubytastic** [comment]
@sushihangover 
Finally managed to try your instructions tonight. After a break from a this project.
My thank you is big for the provided instructions. 
However Im still getting a sources/Script.h:27:29: fatal error: luajit-2.0/lua.h: No such file or directory

To clear things up, I need to clone the luajit-2.0 repo in the MonaServer folder?
I tried this also but then one would need to copy the /src/ folder from Luajit to the root folder of luajit 
not sure that's the way to go.
Hope you can clarify that part.

**Comment by MathieuPOUX** [comment]
Mm should not, no need to clone it in MonaServer folder, if you have
installed it with a "make install" it should be include in os-x system
include folder. Take a look on luajit installation page
<http://luajit.org/install.html> (it describes OS-X case).

2015-04-01 23:29 GMT+02:00 rubytastic <notifications@github.com>:

**Comment by rubytastic** [comment]
Ok , to no avail:
sources/Script.h:27:29: fatal error: luajit-2.0/lua.h: No such file or directory

Also my CentOs 6 gives me hard time, its not easy to compile mona due to the gcc 4.9.
Have to digg more into this.

**Comment by MathieuPOUX** [comment]
After your "make install" operation, where do you find "luajit-2.0/lua.h"
on your centos system? in "/usr/local/include"?

2015-04-02 0:11 GMT+02:00 rubytastic <notifications@github.com>:

**Comment by rubytastic** [comment]
Have started over with clean state. Talking OSX here.
The problem now is not sure to me, bad architecture error? any thoughts?

  "std::cout", referenced from:
      Mona::Application::displayHelp() in Application.o
      Mona::Logger::log(_opaque_pthread_t*, Mona::Logger::Level, char const*, std::string&, long, std::string&) in Logger.o
      Mona::Logger::dump(unsigned char const*, unsigned int) in Logger.o
  "std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)", referenced from:
      Mona::Application::log(_opaque_pthread_t*, Mona::Logger::Level, char const*, std::string&, long, std::string&) in Application.o
      Mona::ServerApplication::handlePidFile(Mona::Exception&, std::string const&) in ServerApplication.o
  "std::basic_ostream<char, std::char_traits<char> >& std::operator<<<std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)", referenced from:
      Mona::Application::log(_opaque_pthread_t*, Mona::Logger::Level, char const*, std::string&, long, std::string&) in Application.o
      Mona::HelpFormatter::flush(std::ostream&) const in HelpFormatter.o
      Mona::HelpFormatter::formatOption(std::ostream&, Mona::Option const&) const in HelpFormatter.o
  "std::basic_ostream<char, std::char_traits<char> >& std::operator<<<std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char)", referenced from:
      Mona::Application::log(_opaque_pthread_t*, Mona::Logger::Level, char const*, std::string&, long, std::string&) in Application.o
      Mona::HelpFormatter::flush(std::ostream&) const in HelpFormatter.o
      Mona::HelpFormatter::formatOptions(std::ostream&) const in HelpFormatter.o
      Mona::HelpFormatter::formatOption(std::ostream&, Mona::Option const&) const in HelpFormatter.o
      Mona::HelpFormatter::formatText(std::ostream&, std::string const&, int) const in HelpFormatter.o
      Mona::HelpFormatter::flushWord(std::ostream&, int&, std::string&, int) const in HelpFormatter.o
  "std::basic_ostream<char, std::char_traits<char> >& std::operator<<<char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      Mona::Application::log(_opaque_pthread_t*, Mona::Logger::Level, char const*, std::string&, long, std::string&) in Application.o
      Mona::HelpFormatter::flush(std::ostream&) const in HelpFormatter.o
      Mona::HelpFormatter::formatOption(std::ostream&, Mona::Option const&) const in HelpFormatter.o
      Mona::HelpFormatter::flushWord(std::ostream&, int&, std::string&, int) const in HelpFormatter.o
  "typeinfo for std::bad_weak_ptr", referenced from:
      std::__throw_bad_weak_ptr() in SocketSender.o
  "vtable for std::bad_weak_ptr", referenced from:
      std::bad_weak_ptr::bad_weak_ptr() in SocketSender.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [release] Error 1
make: *** [release] Error 2

**Comment by rubytastic** [comment]
It seems my system OSX still tries to use the build in gcc. Using the Brew version now. 
I was able to install MonaServer on CentOS correctly. Closing this ticket.

**Comment by rubytastic** [comment]
@MathieuPOUX 
No does not work 
Im still getting the error:

compilation terminated.
make[2]: *** [tmp/Release/Service.o] Error 1
compiling sources/main.cpp
In file included from sources/Service.h:23:0,
                 from sources/MonaServer.h:26,
                 from sources/main.cpp:20:
sources/Script.h:27:29: fatal error: luajit-2.0/lua.h: No such file or directory
  #include "luajit-2.0/lua.h"

The problem is it cannot find the sources of the luajit.
Not quite sure how I could point the makefile to the correct luajit path.

**Comment by MathieuPOUX** [comment]
mm difficult to help here if we don't know where its located lua.h files :(
Try to start search on the entiere disk? after the "make install" step of
lua-jit, necessary you have a "lua.h" somewhere in the include folder of
your system

2015-04-02 12:04 GMT+02:00 rubytastic <notifications@github.com>:

**Comment by rubytastic** [comment]
I understand @MathieuPOUX 
I plan to add a big contribution in test and perhaps also some pull requests. 
I had to install brew luajit also 

Now modified the paths to the luajit source files as hardcoded links like below.
I think that was missing the installed luajit version from brew is causing this not sure. 
I will figure out in the next updates ;)

extern "C" {
	#include "/opt/luajit-2.0/src/lua.h"
	#include "/opt/luajit-2.0/src/lauxlib.h"
}

**Comment by MathieuPOUX** [comment]
Ok thanks for return infos, it's strange that after a "brew install luajit"
the official folder for their includes is "/opt"... We will check, and if
it confirms, we will simply add the "/opt" folder in the makefile here:
https://github.com/MonaSolutions/MonaServer/blob/master/MonaServer/Makefile

2015-04-02 12:20 GMT+02:00 rubytastic <notifications@github.com>:

**Comment by sushihangover** [comment]
FYI: I already had luajit installed as I am using it elsewhere. 

Not sure how you got luajit into /opt using homebrew... all symlinks should be in created within /usr/local/.... homebrew has a policy to never symlink into system space (whenever possible) and the luajit new recipe does not override this policy mindset.

brew link luajit will create links from /usr/local/Cellar/luajit/2.0.3_1...  (that is the version I have installed) to the following:
/usr/local/bin/luajit
/usr/local/bin/luajit-2.0.3
/usr/local/include/luajit-2.0
/usr/local/lib/libluajit-5.1.2.0.3.dylib
/usr/local/lib/libluajit-5.1.2.dylib
/usr/local/lib/libluajit-5.1.a
/usr/local/lib/libluajit-5.1.dylib
/usr/local/lib/pkgconfig/luajit.pc
/usr/local/share/luajit-2.0.3
/usr/local/share/man/man1/luajit.1

FYI: On a clean OS-X 10.x.x install the only item within /opt should be an X11 directory as supplied by Apple (there is historic code within X11 that always assumes /opt/X11 for its own install dir). Of course someone can always use /opt within an autogen prefix and make install, mixing 'local' user code with system code is just a no-no in my book...

**Comment by thomasjammet** [comment]
Thank you robert for your investigation, I think you're right as apple design is really similar to linux.

**Comment by rubytastic** [comment]
Thank you all for the comments, I keep this in mind when updating Mona.
For now it runs fine -as is-
