### ISSUE TITLE
Mona server error

### ISSUE THREAD

**Issue by NickLongooo** [MonaSolutions/MonaServer#92]
I had not used this in a while and it seems to have stopped working I am getting the errors shown below and suspect I am missing something simple. If anyone can offer some suggestions would be greatly appreciated.
Application.cpp[134] MonaServer v2.666
Application.cpp[136] Load configuration file MonaServer.ini
Protocols.h[82] RTMFP server started on 0.0.0.0:1935
Protocols.h[82] RTMP server started on 0.0.0.0:1935
Protocols.h[82] RTMPS server started on 0.0.0.0:8443
Protocols.h[82] HTTP server started on 0.0.0.0:80
Protocols.h[82] WS server started on 0.0.0.0:80
Protocols.h[82] HTTPS server started on 0.0.0.0:443
Protocols.h[82] WSS server started on 0.0.0.0:443
Protocols.h[82] SRT server started on 0.0.0.0:9710
FlashMainStream.cpp[150] Method client releaseStream not found in application /
FlashMainStream.cpp[150] Method client FCPublish not found in application /
I am trying to run a live stream from OBS and when is select start streaming these errors come up
Thanks
Nick

**Comment by thomasjammet** [comment]
Hi Nick!

You can ignore these messages which are just warning you that those functions are not implemented in MonaServer, it is not relevant.
Don't forget to add a pathname in your URL like rtmp://localhost/mypathname/ so that the name of the stream will be correct.

**Comment by NickLongooo** [comment]
Hi Thomas
Thanks for getting back to me, I have sorted it now much appreciated.
NIck
